-- Core CodeLens tables for the first API milestone.
-- IDs use BIGINT identity for simple, sequential references in local/dev tooling.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('STUDENT', 'PROFESSOR'))
);

CREATE TABLE assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    due_date TIMESTAMP NOT NULL,
    professor_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT assignments_professor_id_fkey
        FOREIGN KEY (professor_id) REFERENCES users (id)
);

CREATE TABLE submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    code TEXT NOT NULL,
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT submissions_assignment_id_fkey
        FOREIGN KEY (assignment_id) REFERENCES assignments (id),
    CONSTRAINT submissions_student_id_fkey
        FOREIGN KEY (student_id) REFERENCES users (id),
    CONSTRAINT submissions_assignment_student_key UNIQUE (assignment_id, student_id)
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    reviewer_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    submitted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reviews_submission_id_fkey
        FOREIGN KEY (submission_id) REFERENCES submissions (id),
    CONSTRAINT reviews_reviewer_id_fkey
        FOREIGN KEY (reviewer_id) REFERENCES users (id),
    CONSTRAINT reviews_status_check CHECK (status IN ('DRAFT', 'SUBMITTED')),
    CONSTRAINT reviews_submission_reviewer_key UNIQUE (submission_id, reviewer_id)
);

CREATE INDEX assignments_professor_id_idx ON assignments (professor_id);
CREATE INDEX submissions_assignment_id_idx ON submissions (assignment_id);
CREATE INDEX submissions_student_id_idx ON submissions (student_id);
CREATE INDEX reviews_submission_id_idx ON reviews (submission_id);
CREATE INDEX reviews_reviewer_id_idx ON reviews (reviewer_id);
